language: scala
scala:
- 2.12.8
services:
- docker
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
addons:
  apt:
    packages:
    - sshpass
    - pv
env:
  global:
  - secure: TQxz+xz+KGJZYqkK2m0W9elZf7siEyw/PurEFxpG8fKxQqPlCDhD+91ZAQH3Ifz98IFnyJ8mBhA6zFoIz2lZ/B/Drfw+7E4lzB8xowMMo6x8mkJWhN++l5IAwm20DjBrwhhDyWY9KdC7AEf5eLsaSbf+WL0NHbzm0s2HyNNSyIaQubBkll6eXi3CUtu1q3a0LWkjMZAXFqstfUKcb0uYJ5uqQnsDSTHFVWE5Bk6CwwJabNWFR4PulARAwv4IN2VkFLhQLGiU3psdbihvylz0Ff5vLEO7Y3vcqnluYsipTzawhauf76H5vDeeBw6rP5sNGj0fweb60k9tpJ4mBjQLdHBzZ/54SKG7nPKhmFvv0/yGuX7gNn21BJdIaeVBgG7KGemVefwM4AfMx+877UBBb/7Ojom29pXoCNqmpJzSKjSqZtGLQxdcq7nEHIlDoeMscoCR8UjEB/zvx9P4z895vAFgJ5G97VCe4ZUgt+WvCTTjWyLfQk6H/ckPCWBAzdF3mhPFn2XDlOeFairag1ouIizmLqBjSlE2IvqtJGBN4yCy7+LBbAAzJtd7iKflsGw4WWAaRCfkws3D8x1TOhuWHKdrFvI3zwFDEwCfzNnHcv4iHuiRj9G6m+XRAdUkCI6B20gbtaFEn3UEdK6NecS3reSt6MGNTWpCH99W2jVUEe8=
  - secure: Jk7jEPCikSvL1KDWH24qN0k0iuhGoVZp8ZlPwZApJ/wsC6XDJCnRHFGWmbkApswtn6694pwEUO2/2LPGAy4q2rwHYJo4eb7bsjxj+Ruz+Je7GtgADpAaCZivB2RO+N4FLwWWmRtzFge0TE+FWJF40d5HZLPcCArhoMuV1kZTbkVfRiERxz/r1ZSkN0/46B9rasSO2Jqx+zJ8/t6uMWv8Ncq2ZYbT6uLjn+v3gnDR+120mcUSjOboAejJjDdPSYz2kuScxHS+Cq0yfowtFQHUC2h0gy2x3sEm0VHZsrey8rGQxZmkyfn5mIvxiqx1DK7x4+Kl9mY4BAVsQnEhjceSAWnPmcrQp7klGDF9wkye+lWjWPEpybAYNQumvT62x/W5xV8JWq1wz3ZdycPJw8jXWr3kRdydT8KtzeKmZfo5TzEPTHQVyqEWPOFmD79hYn8jkO9z/wzc5fD5S1Y3Hh0nZfBdhOo+Smd44v9DHSfWlhlNOdoVmPOzmY8cFax1h0w7d5xK5PuhwgJEYYuWyLQAAAKeJ/ScOQ7OdrHnRj3aDh8rIfT05TezMSVja6/NXJCDk2NL51hTBYR1TGck+MvilJF7iyaC4G3/fv6eZEmX9mFcroUig5lO7DmlMIBfaR1PagdfSAzqvXNBE8CmWXNq2MUJpbqGau4S7mjDwJiaaUo=
  - secure: EFuHaqCies3hRApR3/YzbCk3232cCypeIQO92/hzjFf+Xew4NY4UokORIs0q/LYkOyBpE3OoZD5+pYx9eaWl2m4ISVs8NJwnmf2jWK9EDN67QRETXTCws5R2+saCHPfY2T1qtU4KP0V6ptzWCT1krlKJg1ti3dwMQFmJY0eHYFHP2VGP09nvXfnG1sP/HvSx4JodfO1QcqK9NiK5oAeSoewxa4RtQrWr9lMPPTtFhmb0yP1awc/TbXeymUfizERhT1PPtOA41seH40Y1QNYTZcjxwpIED/NagWwoCBeApovKmAREDbGa+fb/q4qJS3YI3tSNyWCKHRNKBR4KJazmePd1zBgdm/BrXnRRnCZH2mbssC+YArvfreOW3qv1PCXdpVmlvtW91fAXEzWqUoA4OqBhQX/77ZFarRiz/redwAF0IvrQW5d2EN96fsR5ItkcVUxFbYTNpF4VaroLuH1liv1hvLvXI5XVuEe0TyCuGSTFei3UhrGYrFys9n3JjAwR0gTOCthM5g5i9TOWUsMtZ009dZjU54tiQ7Te19t/wzTx+HPBUPOaOJmPlUYA4WivUObx0nKnNHmpopCPWVb2ZA6/9DowUfAwdQmHRci62hr522asg6ErVBHwz4Dpw8+zDACjlduyMlNQ/T+Ab0Rc20BtLdUT62pg2kPQ3qx8+cA=
